### ISSUE TITLE
Space Theme Updated (Kinda)

### ISSUE THREAD

**Issue by jack1995CA** [SpaceEnergy/SpaceTheme-Discord#1]
So i made the code more clearer with the annotations by making them tinier so that they are jot so clogged up looking.
[SpaceTheme.zip](https://github.com/SpaceEnergy/SpaceTheme-Discord/files/11691001/SpaceTheme.zip)

**Comment by SpaceEnergy** [comment]
I thank you for your effort but I did it for myself and for people who don't have so much knowledge that they can find something and change it when the theme is finished there will be no comments.
